### ISSUE TITLE
Errors running rm-local-modules

### ISSUE THREAD

**Issue by antun** [ArnaudRinquin/rm-local-modules#1]
I am using Node.js v0.12.2 and NPM 2.7.6. I ran into two separate issues trying to get this module to work:

`Error: Cannot find module '.'
`

... and then:

```
return version.startsWith('file:')
                 ^
TypeError: undefined is not a function
```

Have a PR I'm going to submit.

**Comment by ArnaudRinquin** [comment]
Fixed with #2 and shipped as `0.0.2`. 

Thanks for you contribution and please don't hesitate to ping me next time a miss a PR ;)
